services:
- docker

deploy:
  provider: script
  script: bash scripts/deploy.sh
  before_script: 
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    - openssl aes-256-cbc -K $encrypted_4929b6acbf68_key -iv $encrypted_4929b6acbf68_iv
      -in 2019_1_HotCode_id_rsa.pem.enc -out ./2019_1_HotCode_id_rsa.pem -d
  on:
    branch: continuous-deploy-tests