language: go
go:
- '1.12'
script:
- go build .
- chmod 600 ./2019_1_HotCode_id_rsa.pem
- ssh-keyscan -H 89.208.198.192 >> ~/.ssh/known_hosts
- scp -i ./2019_1_HotCode_id_rsa.pem ./warscript-users ubuntu@89.208.198.192:/home/ubuntu/production-back
branches:
  only:
  - continuous-deploy-tests
before_install:
- openssl aes-256-cbc -K $encrypted_4929b6acbf68_key -iv $encrypted_4929b6acbf68_iv
  -in 2019_1_HotCode_id_rsa.pem.enc -out ./2019_1_HotCode_id_rsa.pem -d
